receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch-svc:9200"]
    index: "otel-logs-%{+yyyy.MM.dd}"

  jaeger:
    endpoint: jaeger-svc:14250
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: flask_app

  debug: {}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
