receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  # --- Logs to Elasticsearch (ELK) ---
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "otel-logs"

  # --- Traces to Jaeger ---
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # --- Metrics to Prometheus ---
  prometheus:
    endpoint: 0.0.0.0:9464   # Prometheus will scrape this
    namespace: flask_app     # prefix for metric names

  debug: {}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
