receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlphttp/loki:
    endpoint: http://loki-svc:3100/otlp
    tls:
      insecure: true
  otlp/tempo:                # <-- changed to gRPC exporter
    endpoint: tempo-svc:4317
    tls:
      insecure: true
  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]   # <-- using gRPC exporter
